spring.application.name=springboot-backend-linkoria

spring.datasource.url=jdbc:mysql://localhost:3306/chatapp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sasa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

#codigo secreto para desarrollo TODO: cambiarlo cuando este en produccion
app.jwt.secret=l1nk0r1a-s3cr3t-k3y-p4r4-JWT-d3s4rr0ll0-2026